title: ron4ex
author: https://github.com/ron4ex
description: > # this means to ignore newlines until "baseurl:"
  Personal corner on the web of the person who goes by the name Ronak Baldha (ron4ex)
baseurl: ""
google_analytics: UA-90015621-1
disqus:
  shortname: onak

# Build settings
markdown: kramdown
# theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
