title: r.onak
author: https://github.com/ron4ex
description: > # this means to ignore newlines until "baseurl:"
  Web address of the person who goes by the name Ronak Baldha
baseurl: ""
google_analytics: UA-90015621-1

# Build settings
markdown: kramdown
# theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
