# Site settings
title: "r.onak.in"
email: ronak.baldha@gmail.com
description: "Jekyll Powered Personal Blog (Experimental)"
# Local
baseurl: ""
# Live
# baseurl: "http://ron4ex.github.io"
url: "http://ron4ex.github.io"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://secure.gravatar.com/avatar/276b0af29760b43c0f78494ad0a4be92"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: _jacobtomlinson
github_username:  jacobtomlinson
linkedin_link: http://carte-noire.jacobtomlinson.co.uk/
google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
footer_left: "With <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; forked from <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
encoding: utf-8
highlighter: rouge
markdown: kramdown
github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
#permalink: pretty
#exclude: [vendor]
