# Site settings
title: "r.onak.in"
email: ronak.baldha@gmail.com
description: "Ronakin rhymes with Anakin"

# Local
baseurl: ""
# Live
# baseurl: "http://ron4ex.github.io"
url: "http://ron4ex.github.io"

title_description: "A dot too many in the title perhaps? Hey! I'm Ronak and this is my space, not MySpace but my space with a space. Such ramblings of a vella brain! Please ignore 145 characters that preceded this sentence. I'm Ronak, you can call me Ron. And this is where I hope to be posting some good stuff. Hope I don't bore you!"
title_image: "http://www.gravatar.com/avatar/276b0af29760b43c0f78494ad0a4be92?s=200"

google_analytics: "UA-73293555-1"
disqus_account: ronakin
github_repository: https://github.com/ron4ex/ron4ex.github.io
addthis_id: ra-56b25ba0d95d5f5d
post_limit: 5

# Social usernames/URLs
twitter_username: bababurgundy
github_username:  ron4ex
linkedin_link: 
google_plus_link: https://plus.google.com/u/0/113495328077291040017
stackoverflow_link: 

# Footer
footer_left: "With <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/bababurgundy\">Ronak Baldha</a>"
footer_right: "&lt;/&gt; forked from <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
encoding: utf-8
highlighter: rouge
markdown: kramdown
github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
#redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
#permalink: pretty
#exclude: [vendor]
